# Generated by Django 5.2.6 on 2025-09-11 20:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in lbs')),
                ('bmi', models.FloatField()),
                ('blood_pressure', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('cholesterol', models.FloatField(blank=True, null=True)),
                ('glucose', models.FloatField(blank=True, null=True)),
                ('insulin', models.FloatField(blank=True, null=True)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('sleep_hours', models.FloatField()),
                ('sleep_quality', models.CharField(max_length=20)),
                ('work_hours', models.FloatField()),
                ('physical_activity', models.FloatField()),
                ('daily_steps', models.IntegerField()),
                ('calorie_intake', models.FloatField()),
                ('alcohol_consumption', models.CharField(max_length=20)),
                ('smoking_level', models.CharField(max_length=20)),
                ('water_intake', models.FloatField()),
                ('diet_type', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(max_length=100)),
                ('sunlight_exposure', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
